StampyAI/stampy-chat

api/chat.py
api/followups.py
web/src/pages/index.tsx
web/src/searchbox.tsx

Minimum viable product of #16. All the more advanced features discussed there and other places will come next, chief among which being a way to display responses in-situ instead of linking to an external stampy page.

MVP Suggest Human-Authored Follow-Up Questions

---

api/main.py
web/src/logo.svg
web/src/pages/index.tsx
web/src/pages/semantic.tsx
web/src/searchbox.tsx
web/src/styles/globals.css

closes #16 I think. Needs more hands to try out the new workflow, since this is a fairly major shift.

In text view of suggested human-authored follow-up questions

---

api/chat.py
api/main.py

Use as such
```
https://alignmentsearch-api.up.railway.app/chat/In%2030%20words%20or%20less%2C%20what%20is%20a%20mesa-optimizer%3F
```
```json
{
"response": "A mesa-optimizer is an optimizer that is itself being optimized by another optimizer, found autonomously by a base optimizer. [b]",
"citations": {
"a": {
"title": "Is the term mesa optimizer too narrow?",
"author": "Matthew Barnett",
"date": "2019-12-14",
"url": "https://www.lesswrong.com/posts/nFDXq7HTv9Xugcqaw/is-the-term-mesa-optimizer-too-narrow"
},
"b": {
"title": "[AN #58] Mesa optimization: what it is, and why we should care",
"author": "Rohin Shah",
"date": "2019-06-24",
"url": "https://www.lesswrong.com/posts/XWPJfgBymBbL3jdFd/an-58-mesa-optimization-what-it-is-and-why-we-should-care"
},
"c": {
"title": "Utility ≠ Reward", …
```

Simplified api endpoint

---

.github/workflows/deploy-to-production.yml
api/Pipfile
web/src/pages/index.tsx

This PR fixes every issue that was impacting production and will make it so any future changes to the main branch are automatically deployed to production.
Fixes #43 
Fixes #7

Make Production Ready

---

readme.md
web/src/header.tsx
web/src/pages/index.tsx
web/src/pages/semantic.tsx

Updated header with stampy logo and text. Also included instructions to access private ARD.
Closes #49

update header, ard-private readme

---

api/chat.py
api/main.py
web/src/pages/index.tsx

closes #33 .
Let's keep the discussion on this PR just on the technical implementation. I expect we'll want to discuss what exact modes to implement synchronously in a live meeting since that relates more to project direction - better to have a full speed back and forth \:)

create level modes

---

api/main.py
web/src/header.tsx
web/src/pages/index.tsx
web/src/pages/semantic.tsx
web/src/searchbox.tsx

internal ai.safety.info links handled correctly 

---

readme.md
web/src/pages/index.tsx

accidentally missed this one the first time around

also fall back to duckduckgo on in-text citations

---

web/src/glossary.tsx
web/src/pages/_app.tsx
web/src/pages/index.tsx
web/src/styles/globals.css

Inject glossary into generated answers

---

web/src/glossary.tsx
web/src/header.tsx
web/src/pages/index.tsx
web/src/pages/semantic.tsx
web/src/searchbox.tsx

React and JSX tend to have a lot of deeply indented code, and in the community 2-space indentation is pretty common. Since I'm the primary (only) dev working on the codebase, I'm going to take the initiative here and swap stuff over.
Will convert from a draft to a real PR after we merge #73.

Indentation fix

---

api/chat.py
web/src/pages/index.tsx

implement moderation

---

api/src/stampy_chat/chat.py
api/src/stampy_chat/env.py
api/src/stampy_chat/get_blocks.py
web/src/pages/index.tsx
web/src/pages/semantic.tsx

Handles both the old and new pinecone, as there are slight differences in dates and authors. Will require the appropriate env variables to be set

Use new pinecone embeddings

---

README.md
api/.env.example
api/Pipfile
api/Pipfile.lock
api/migrations/README
api/migrations/alembic.ini
api/migrations/env.py
api/migrations/script.py.mako
api/migrations/versions/78806d965229_interactions_table.py
api/setup.py
api/src/stampy_chat/db/models.py
api/src/stampy_chat/db/session.py
api/src/stampy_chat/env.py
local_db.sh

This is just the MySQL handling stuff, no actual usage

MySQL support

---

api/.env.example
api/main.py
api/src/stampy_chat/chat.py
api/src/stampy_chat/env.py
api/src/stampy_chat/followups.py
api/src/stampy_chat/get_blocks.py
api/src/stampy_chat/logging.py

Adds a logger that:
* handles all normal logging thingies
* is controllable via the `LOG_LEVEL` env variable
* will send all messages that it receives on to Discord if the message is from a `stampy_chat` module and it has a level at least at `DISCORD_LOG_LEVEL`
* will create appropriate MySQL entries for each interaction

Log to mysql

---

web/src/hooks/useSearch.ts
web/src/pages/index.tsx
web/src/settings.ts

* Move search functions to separate file
* Simplify search functions
* Move Stampy URL cleaning to frontend
* Configurable search endpoints via settings

Cleanup search

---

api/main.py
api/src/stampy_chat/chat.py
api/src/stampy_chat/logging.py
web/src/hooks/useSearch.ts
web/src/pages/index.tsx

This just adds a session id so the logging will have a proper history. Future expansions would be:
* sharing chats by providing the session id as a parameter
* continuing chats by providing the session id as a parameter ; this one could be tricky - should it continue the original session id, or create a new session but prepending the previous ones?
* removal of sessions by id

Session ids

---

.github/workflows/pytest.yml
api/Pipfile
api/Pipfile.lock
api/src/stampy_chat/followups.py
api/src/stampy_chat/get_blocks.py
api/src/stampy_chat/logging.py
api/tests/stampy_chat/test_followups.py
api/tests/stampy_chat/test_get_blocks.py
api/tests/stampy_chat/test_logging.py

Adds a load more tests + a bit of refactoring a couple of functions (mainly splitting them into smaller ones)

More tests

---

web/package.json
web/src/components/assistant.tsx
web/src/components/citations.tsx
web/src/components/entry.tsx
web/src/components/glossary.tsx
web/src/components/header.tsx
web/src/components/html.tsx
web/src/components/page.tsx
web/src/components/searchbox.tsx
web/src/hooks/useSearch.ts
web/src/pages/_app.tsx
web/src/pages/index.tsx
web/src/pages/semantic.tsx
web/src/settings.ts
web/src/styles/globals.css
web/src/types.ts

Adds linters and prettier. Only the commands for now + fixes, but that still is a lot...

fix typescript errors

---

api/src/stampy_chat/db/session.py

https://github.com/StampyAI/stampy-chat/issues/118

Handle MySQL errors

---

web/src/hooks/useCitations.ts
web/src/hooks/useSearch.ts
web/src/hooks/useSettings.ts
web/src/pages/tester.tsx

Allows testing of all sample questions at once. Otherwise known as DDOS fun :D

Test multiple questions

---

web/src/components/chat.tsx
web/src/components/citations.tsx
web/src/styles/globals.css
web/src/types.ts

also https://github.com/StampyAI/stampy-chat/issues/130

Show quotes

---

api/.env.example
api/main.py
api/src/stampy_chat/chat.py
api/src/stampy_chat/env.py

added the code so that the interactions of the user with stampy in https://chat.stampy.ai/ are logged in langsmith to be able to monitor how the users interact with the chatbot

added langsmith code

---

api/src/stampy_chat/citations.py
api/src/stampy_chat/prompts.py
mprocs.yaml
prompts/detailed-cautious-epistem-safetyinfo-v6-2508050537-3644ff.txt
web/src/components/assistant.tsx
web/src/components/chat.tsx
web/src/components/html.tsx
web/src/components/settings.tsx
web/src/hooks/useSearch.ts
web/src/hooks/useSettings.ts
web/src/types.ts

Please merge-then-edit rather than adding round trip latency waiting for me to tidy things. written at midnight

Several prompting changes, and expose HyDE and thinking in UI

---

.ctrlp_ignore
CLAUDE.md
web/src/hooks/useSettings.ts

- move to hash instead of query string so it doesn't get sent to the server and make the server mad when the url is really really long
- debounce so it doesn't change on keystroke
- split in settings file so changes are more obvious

Fix some issues with how storing params in the url are handled

---

api/main.py
api/src/stampy_chat/callbacks.py

so they're not a single big blob of everything

fix sentry error messages
